/* ------------------------------------------- */
/* Author: Arthur Damböck                      */
/* Date: 2025/2026                             */
/* ------------------------------------------- */

#ifndef MICROSIMULATION_EDITOR_H
#define MICROSIMULATION_EDITOR_H

#include <QPushButton>
#include <QWidget>
#include <Qsci/qsciscintilla.h>
#include <Qsci/qscilexercpp.h>
#include <Qsci/qscilexercustom.h>
#include "../controller/editor_controller.h"

QT_BEGIN_NAMESPACE

// Forward declaration of the class generated by uic
namespace Ui { class editor; }

QT_END_NAMESPACE

namespace gui::views {
    class editor : public QWidget {
        Q_OBJECT

    public:
        explicit editor(QWidget *parent = nullptr);

        void reset_all();

        ~editor() override;
    private slots:
        void run_parser();

    private:
        Ui::editor *ui;
        QsciScintilla * m_editor;
        QsciLexerCustom* m_lexer;
        editor_controller * m_controller;
        QPushButton * m_compile_btn;
        QPushButton * m_reset_btn;

    };
}

using editor = gui::views::editor;

#endif //MICROSIMULATION_EDITOR_H